<script type="text/javascript">
    $(document).ready(function() {
        
        $("#datepicker_from").datepicker({
            dateFormat: "yy-mm-dd"
        });
        
        $("#datepicker_to").datepicker({
            dateFormat: "yy-mm-dd"
        });


        $("#payment_method_format").buttonset();
        $("#states_format").buttonset();
        
    });    
        
</script>

<div id="dates_panel" class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-calendar fa-fw"></i> Fecha
        <div class="pull-right">
            <div class="btn-group">
                <span class="pull-right clickable"><i class="fa fa-chevron-up"></i></span>
            </div>
        </div>
    </div>
    <div class="panel-body">
        Desde:
        <input type="text" id="datepicker_from"> Hasta:
        <input type="text" id="datepicker_to">
    </div>
</div>