<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard <small><?php echo $this->getCurrentMonthName(); ?> <?php echo $this->getCurrentYear(); ?></small></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-4 col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            <?php echo $this->getNewCustomers(); ?></div>
                        <div>
                            <?php echo $this->__('Nuevos usuarios'); ?></div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->__('Detalles'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-8">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-2">
                        <i class="fa fa-usd fa-5x"></i>
                    </div>
                    <div class="col-xs-10 text-right">
                        <div class="huge">
                            <?php echo $this->getSales(); ?></div>
                        <div>
                            <?php echo $this->__('Ventas'); ?></div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->__('Detalles'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-8">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            <?php echo $this->getNewOrders(); ?></div>
                        <div>
                            <?php echo $this->__('Nuevas ordenes'); ?></div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><?php echo $this->__('Detalles'); ?></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i>
                <?php echo $this->__('Ventas '.$this->getCurrentMonthName().' '.$this->getCurrentYear()); ?>
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Opciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="javascript:drawChart(amountData);">Monto</a>
                            </li>
                            <li><a href="javascript:drawChart(qtyData);">Ordenes</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="chart_div"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-8 -->
</div>
<!-- /.row -->

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">

    var amountData = new Array();
    var qtyData = new Array();

    google.load('visualization', '1', {
        packages: ['corechart', 'bar']
    });
    google.setOnLoadCallback(getData);

    function getCheckBoxFilter(attributeName) {

        var status = new Array();

        var chk_arr = document.getElementsByName(attributeName);
        var chklength = chk_arr.length;

        for (var k = 0; k < chklength; k++) {
            if (chk_arr[k].checked === true) {
                status.push(chk_arr[k].id);
            }
        }

        return status;

    }

    function getData() {

        $("#datepicker_from").datepicker({
            dateFormat: "yy-mm-dd"
        });
        $("#datepicker_to").datepicker({
            dateFormat: "yy-mm-dd"
        });

        var status = getCheckBoxFilter("status[]");
        var paymentMethod = getCheckBoxFilter("payment_method[]");
        var state = getCheckBoxFilter("state[]");

        $.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('reports/salesData/getSalesByDay'); ?>",
            data: {
                date_from: '2013-12-01', //$("#datepicker_from").val(),
                date_to: '2013-12-31', //$("#datepicker_to").val(),
                status: status,
                payment_method: paymentMethod,
                state: state
            },
            dataType: 'json',
            success: function(data) {

                var amountHeader = new Array(2);
                amountHeader[0] = 'Periodo';
                amountHeader[1] = 'Monto [ARS]';

                amountData.push(amountHeader);
                
                var qtyHeader = new Array(2);
                qtyHeader[0] = 'Periodo';
                qtyHeader[1] = '# Ordenes';
                qtyData.push(qtyHeader);

                var days = Object.keys(data);
                
                days.sort();
                
                for (var day in days) {

                    var amountRow = new Array();

                    amountRow[0] = days[day];
                    amountRow[1] = parseFloat(data[days[day]].amount);

                    amountData.push(amountRow);
                    
                    var qtyRow = new Array();

                    qtyRow[0] = days[day];
                    qtyRow[1] = parseInt(data[days[day]].qty, 10);

                    qtyData.push(qtyRow);

                }

                drawChart(amountData);

            }
        });

    }

    function drawChart(rawData) {

        var data = google.visualization.arrayToDataTable(rawData);

        var options = {
            title: 'Ventas',
            height: 500,
            width: 1000
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

        chart.draw(data, options);
    }
</script>