<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
google.load('visualization', '1', {
    packages: ['corechart', 'bar']
});
google.setOnLoadCallback(getData);

function getCheckBoxFilter(attributeName) {
    
    var status = new Array();
            
    var chk_arr =  document.getElementsByName(attributeName);
    var chklength = chk_arr.length;             
            
    for( var k=0;k< chklength;k++) {
        if ( chk_arr[k].checked === true ) {
            status.push(chk_arr[k].id);
        }
    }
    
    return status;
    
}

function getData() {
    
    $( "#datepicker_from" ).datepicker( { dateFormat: "yy-mm-dd" } );
    $( "#datepicker_to" ).datepicker( { dateFormat: "yy-mm-dd" } );
    
    debugger;
    var status = getCheckBoxFilter("status[]");
    var paymentMethod = getCheckBoxFilter("payment_method[]");
    var state = getCheckBoxFilter("state[]");

    $.ajax({
        type: "POST",
        url: "<?php echo Mage::getUrl('reports/salesData/getSalesByDate'); ?>",
        data: { 
                date_from:  $( "#datepicker_from" ).val(), 
                date_to :  $( "#datepicker_to" ).val(),
                status: status,
                payment_method: paymentMethod,
                state: state} ,
        dataType: 'json',
        success: function(data) {

            var newData = new Array();

            var header = new Array(2);
            header[0] = 'Periodo';
            header[1] = 'Monto [ARS]';

            newData.push(header);

            var years = Object.keys(data);

            for ( var year in years ) {
                var months = Object.keys(data[years[year]]);
                
                months.sort();
                
                for ( var month in months ) {
                    
                    var newRow = new Array();

                    newRow[0] = years[year] + '-' + months[month]; //data[year][month].period;
                    newRow[1] = parseFloat(data[years[year]][months[month]].amount);
                            
                    newData.push(newRow);
                }
                
            }
            
            /* for (var year in data) {
                if (data.hasOwnProperty(year)) {
                    
                    for (var month in data[year]) {
                        if (data[year].hasOwnProperty(month)) {
                            
                            var newRow = new Array();

                            newRow[0] = new Date(year, month, '01'); //month + "-" + year; //data[year][month].period;
                            newRow[1] = parseFloat(data[year][month].amount);
                            
                            newData.push(newRow);
                            
                        }
                        
                    }
                    
                    var newRow = new Array();

                    newRow[0] = data[i].period;
                    newRow[1] = parseFloat(data[i].amount);
                    
                    newData.push(newRow); */
                   
                   
                   
                  //console.log(key, yourobject[key]);
                //}
                
                //data[year].sort();
                //debugger;
                //var sortedData = Object.keys(data).sort( function(keyA, keyB) {
                //    return data[keyA] - data[keyB];
                //});
                
            //}
            //debugger;
            //newData.sort(function (a, b) { return a[0] === b[0] });

            /* for (var i = 0; i < data.length; i++) {

                var newRow = new Array();

                newRow[0] = data[i].period;
                newRow[1] = parseFloat(data[i].amount);

                newData.push(newRow);


            } */

            drawChart(newData);

            //createTable(data);

        }
    });

}

function drawChart(rawData) {

    /*var data = google.visualization.arrayToDataTable([
        ['City', '2010 Population', ],
        ['New York City, NY', 8175000],
        ['Los Angeles, CA', 3792000],
        ['Chicago, IL', 2695000],
        ['Houston, TX', 2099000],
        ['Philadelphia, PA', 1526000]
    ]); */
    
    var data = google.visualization.arrayToDataTable(rawData);

    var options = {
                title: 'Ventas por mes',
                height: 500
            };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

    chart.draw(data, options);
}

</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Ventas por Mes</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
          <div id="chart_div"></div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
          <?php echo $this->getChildHtml('filters') ?>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<style>
.panel-heading span {
    margin-top: -20px;
    font-size: 15px;
}
.row {
    margin-top: 40px;
    padding: 0 10px;
}
.clickable {
    cursor: pointer;
}    
</style>

<script type="text/javascript">
    jQuery(function ($) {
        $('.panel-heading span.clickable').on("click", function (e) {
            if ($(this).hasClass('panel-collapsed')) {
                // expand the panel
                $(this).parents('.panel').find('.panel-body').slideDown();
                $(this).removeClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            }
            else {
                // collapse the panel
                $(this).parents('.panel').find('.panel-body').slideUp();
                $(this).addClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');
            }
        });
    });
</script>