<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
google.load('visualization', '1', {
    packages: ['corechart', 'bar']
});
google.setOnLoadCallback(drawBasic);

function getData() {
    
    $( "#datepicker_from" ).datepicker( { dateFormat: "yy-mm-dd" } );
    $( "#datepicker_to" ).datepicker( { dateFormat: "yy-mm-dd" } );

    $.ajax({
        type: "POST",
        url: "<?php echo Mage::getUrl('reports/salesData/getSalesByDate'); ?>",
        data: { 
                date_from:  $( "#datepicker_from" ).val(), 
                date_to :  $( "#datepicker_to" ).val() },
                //status: status,
                //payment_method: paymentMethod } ,
        dataType: 'json',
        success: function(data) {

            var newData = new Array();

            var header = new Array(2);
            header[0] = 'Periodo';
            header[1] = 'Monto [ARS]';

            newData.push(header);

            for (var i = 0; i < data.length; i++) {

                var newRow = new Array();

                newRow[0] = data[i].period;
                newRow[1] = parseFloat(data[i].amount);

                newData.push(newRow);


            }

            drawChart(newData);

            createTable(data);

        }
    });

}

function drawBasic() {

    var data = google.visualization.arrayToDataTable([
        ['City', '2010 Population', ],
        ['New York City, NY', 8175000],
        ['Los Angeles, CA', 3792000],
        ['Chicago, IL', 2695000],
        ['Houston, TX', 2099000],
        ['Philadelphia, PA', 1526000]
    ]);

    var options = {
        title: 'Population of Largest U.S. Cities',
        chartArea: {
            width: '50%'
        },
        hAxis: {
            title: 'Total Population',
            minValue: 0
        },
        vAxis: {
            title: 'City'
        }
    };

    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

    chart.draw(data, options);
}

</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Ventas por provincia</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
          <div id="chart_div"><div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
          <?php echo $this->getChildHtml('filters') ?>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
          <?php echo $this->getChildHtml('filters') ?>
    </div>
</div>    

<style>
.panel-heading span {
    margin-top: -20px;
    font-size: 15px;
}
.row {
    margin-top: 40px;
    padding: 0 10px;
}
.clickable {
    cursor: pointer;
}    
</style>

<script type="text/javascript">
    jQuery(function ($) {
        $('.panel-heading span.clickable').on("click", function (e) {
            if ($(this).hasClass('panel-collapsed')) {
                // expand the panel
                $(this).parents('.panel').find('.panel-body').slideDown();
                $(this).removeClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            }
            else {
                // collapse the panel
                $(this).parents('.panel').find('.panel-body').slideUp();
                $(this).addClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');
            }
        });
    });
</script>