<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
    google.load('visualization', '1', {
        packages: ['corechart', 'bar']
    });
    google.setOnLoadCallback(getData);

    function getCheckBoxFilter(attributeName) {

        var status = new Array();

        var chk_arr = document.getElementsByName(attributeName);
        var chklength = chk_arr.length;

        for (var k = 0; k < chklength; k++) {
            if (chk_arr[k].checked === true) {
                status.push(chk_arr[k].id);
            }
        }

        return status;

    }

    function getData() {

        $("#datepicker_from").datepicker({
            dateFormat: "yy-mm-dd"
        });
        $("#datepicker_to").datepicker({
            dateFormat: "yy-mm-dd"
        });

        var status = getCheckBoxFilter("status[]");
        var paymentMethod = getCheckBoxFilter("payment_method[]");
        var state = getCheckBoxFilter("state[]");

        $.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('reports/customersData/getCustomersByLastOrder'); ?>",
            data: {
                date_from: $("#datepicker_from").val(),
                date_to: $("#datepicker_to").val(),
                status: status,
                payment_method: paymentMethod,
                state: state
            },
            dataType: 'json',
            success: function(data) {

                var newData = new Array();

                var row = new Array();
                row[0] = "Meses";
                row[1] = "Clientes";

                newData.push(row);

                for (var i = 0; i < data.length; i++) {
                    row = new Array();

                    if (data[i].months == 13) {
                        row[0] = String(">12");
                    }
                    else {
                        row[0] = String(data[i].months);
                    }

                    row[1] = parseInt(data[i].qty, 10);

                    newData.push(row);
                }

                drawChart(newData);

            }
        });

    }

    function drawChart(rawData) {

        var data = google.visualization.arrayToDataTable(rawData);

        var options = {
            title: 'Última orden',
            height: 500,
            hAxis: {
                title: 'Meses'
            }
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        chart.draw(data, options);

    }
    
</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->__('Ultimas Ordenes'); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">Action</a>
                            </li>
                            <li><a href="#">Another action</a>
                            </li>
                            <li><a href="#">Something else here</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="chart_div">
                    <img src="http://jimpunk.net/Loading/wp-content/uploads/loading18.gif" />
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->getChildHtml('filters') ?>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<script type="text/javascript">
    jQuery(function($) {
        $('.panel-heading span.clickable').on("click", function(e) {
            if ($(this).hasClass('panel-collapsed')) {
                // expand the panel
                $(this).parents('.panel').find('.panel-body').slideDown();
                $(this).removeClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            }
            else {
                // collapse the panel
                $(this).parents('.panel').find('.panel-body').slideUp();
                $(this).addClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');
            }
        });
    });
</script>