<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
    google.load('visualization', '1', {
        packages: ['corechart', 'bar']
    });
    google.setOnLoadCallback(getData);

    function getCheckBoxFilter(attributeName) {

        var status = new Array();

        var chk_arr = document.getElementsByName(attributeName);
        var chklength = chk_arr.length;

        for (var k = 0; k < chklength; k++) {
            if (chk_arr[k].checked === true) {
                status.push(chk_arr[k].id);
            }
        }

        return status;

    }

    function getData() {

        $("#datepicker_from").datepicker({
            dateFormat: "yy-mm-dd"
        });
        $("#datepicker_to").datepicker({
            dateFormat: "yy-mm-dd"
        });

        var status = getCheckBoxFilter("status[]");
        var paymentMethod = getCheckBoxFilter("payment_method[]");
        var state = getCheckBoxFilter("state[]");

        $.ajax({
            type: "POST",
            url: "<?php echo Mage::getUrl('reports/customersData/getNewVsExistingCustomers'); ?>",
            data: {
                date_from: $("#datepicker_from").val(),
                date_to: $("#datepicker_to").val(),
                status: status,
                payment_method: paymentMethod,
                state: state
            },
            dataType: 'json',
            success: function(data) {
                
                var dataTablesArray = new Array();

                var newData = new Array();
                
                var pieChartData = new Array();
                var pieChartRow = new Array(2);
                pieChartRow[0] = 0;
                pieChartRow[1] = 0;

                var header = new Array(3);
                header[0] = 'Periodo';
                header[1] = 'Nuevos';
                header[2] = 'Existentes';

                newData.push(header);

                var periods = Object.keys(data);

                for (var period in periods) {

                    var newRow = new Array();

                    newRow[0] = periods[period];
                    newRow[1] = parseInt(data[periods[period]].newCustomers, 10);
                    newRow[2] = parseInt(data[periods[period]].existingCustomers, 10);
                    
                    pieChartRow[0] += newRow[1];
                    pieChartRow[1] += newRow[2];

                    newData.push(newRow);
                    
                    var dataTablesObj = { period: periods[period], 
                                          newClients: parseInt(data[periods[period]].newCustomers, 10), 
                                          existingClients: parseInt(data[periods[period]].existingCustomers, 10) };
                        
                    dataTablesArray.push(dataTablesObj);

                }
                
                var pieChartHeader = new Array(2);
                pieChartHeader[0] = 'Cliente';
                pieChartHeader[1] = 'Compras';
                pieChartData.push(pieChartHeader);
                
                pieChartHeader = new Array(2);
                pieChartHeader[0] = 'Nuevos';
                pieChartHeader[1] = pieChartRow[0];
                pieChartData.push(pieChartHeader);
                
                pieChartHeader = new Array(2);
                pieChartHeader[0] = 'Existentes';
                pieChartHeader[1] = pieChartRow[1];
                pieChartData.push(pieChartHeader);

                drawChart(newData);
                
                drawPieChart(pieChartData);

                createTable(dataTablesArray);

            }
        });

    }
    
    function drawPieChart(rawData) {

        var data = google.visualization.arrayToDataTable(rawData);

        var options = {
            title: 'Nuevos vs Existentes',
            height: 500
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_div'));

        chart.draw(data, options);
    }

    function drawChart(rawData) {

        var data = google.visualization.arrayToDataTable(rawData);

        var options = {
            height: 500,
            legend: {
                position: 'top',
                maxLines: 3
            },
            bar: {
                groupWidth: '75%'
            },
            isStacked: true,
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
    
    function createTable(jsonData) {
        
        $('#datatable').dataTable({
            retrieve: true,
            "aaData": jsonData,
            "aoColumns": [{
                "mDataProp": "period"
            }, {
                "mDataProp": "newClients"
            }, {
                "mDataProp": "existingClients"
            }]
        });
    }
    
</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->__('Clientes nuevos vs existentes'); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Opciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="javascript:formatData('amount');">Monto</a>
                            </li>
                            <li><a href="javascript:formatData('qtyPerOrder');">Cantidad</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="chart_div"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Opciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="javascript:formatData('amount');">Monto</a>
                            </li>
                            <li><a href="javascript:formatData('qtyPerOrder');">Cantidad</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="piechart_div"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                DataTables Advanced Tables
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table id="datatable" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Periodo</th>
                                <th>Clientes Nuevos</th>
                                <th>Clientes Existentes</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->getChildHtml('filters') ?>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<script type="text/javascript">
    jQuery(function($) {
        $('.panel-heading span.clickable').on("click", function(e) {
            if ($(this).hasClass('panel-collapsed')) {
                // expand the panel
                $(this).parents('.panel').find('.panel-body').slideDown();
                $(this).removeClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            }
            else {
                // collapse the panel
                $(this).parents('.panel').find('.panel-body').slideUp();
                $(this).addClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');
            }
        });
    });
</script>