<script type="text/javascript">

    function getData() {
        
        $.ajax({
                type: 'POST',
                url: "<?php echo Mage::getUrl('reports/data/getAvgByCustomer'); ?>",
                dataType: 'json',
                success: function(data) {

                    var newData = new Array();

                    var row = new Array();
                    row[0] = "Periodo";
                    row[1] = "Monto [ARS]";
                    
                    newData.push(row);
 
                    for (var i = 0; i < data.length; i++) {
                        row = new Array();
                        
                        row[0] = data[i].period;
                        row[1] = parseFloat(data[i].average);
                            
                        newData.push(row);
                    }

                    drawChart(newData);

                }
            });
        
    }

    google.load("visualization", "1", {
        packages: ["corechart"]
    });
    google.setOnLoadCallback(getData);

    function drawChart(rawData) {

        var data = google.visualization.arrayToDataTable(rawData);

        var options = {
            title: 'Gasto Total Promedio',
            hAxis: {
                title: 'Periodo',
                titleTextStyle: {
                    color: 'red'
                }
            }
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        chart.draw(data, options);

    }
</script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<?php
/*
$storeId    = Mage::app()->getStore()->getId();

$products = Mage::getResourceModel('reports/product_collection')
            ->addOrderedQty()
            ->addAttributeToSelect(array('name', 'price', 'small_image')) //edit to suit tastes
            ->setStoreId($storeId)
            ->addStoreFilter($storeId)
            ->setOrder('ordered_qty', 'desc'); //best sellers on top

Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($products);
Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($products);

print_r($products->getData()); */

?>