<h1 class="page-header">Cohort Analysis</h1>

<div id="main-example"></div>

<script type="text/javascript" src="http://104.131.22.107/bigData/js/cornelius.js"></script>

<script type="text/javascript">
  var data = [
          [1973, 1000, 750, 300, 400, 70, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
          [1268, 549, 336, 221, 122, 115, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
          [1892, 1282, 250, 32, 18, 10, 9, 8, 7, 6, 5, 4, 3, 2],
          [1832, 379, 254, 314, 10, 9, 8, 7, 6, 5, 4, 3],
          [1171, 256, 120, 10, 9, 8, 7, 6, 5, 4],
          [2533, 340, 10, 9, 8, 7, 6, 5]
      ];
      // The initial date is the date displayed
      // in the first column of the first row
      
  $(document).ready(function() {

      var menuLink = document.getElementById("menu_cohort_analysis");
      menuLink.className = "active";
      
      $.ajax({
                type: 'POST',
                url: "<?php echo Mage::getUrl('reports/data/getCohortData'); ?>",
                dataType: 'json',
                success: function(data) {

                  var newData = new Array();

                  for (var i = 0; i < data.length; i++) {
                    
                    newData[i] = new Array();
                    
                    var array = $.map(data[i], function(value, index) {
                        return [value];
                    });
                    
                    newData[i][0] = parseInt(array[0].customers, 10);
                    
                    for ( var j = 0; j < array.length; j++ ) {
                      newData[i][j+1] = parseFloat(array[j].amount);
                    }
                    
                  }
                  
                  initialDate = new Date(2012, 0),

      // DOM Element where the Cohort Chart will be inserted
      container = document.getElementById('main-example');

  Cornelius.draw({
      initialDate: initialDate,
      container: container,
      cohort: newData,
      title: 'Cornelius Demo',
      timeInterval: 'yearly'
  });


                }
            });

  });
</script>