<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>

<script type="text/javascript">
function getData() {
    $.ajax({
        type: 'POST',
        url: '<?php echo Mage::getUrl('helloworld/index/getNewCustomersByDate'); ?>',
        dataType: 'json',
        success: function(data) {
            var newData = new Array();

            for (var i = 0; i < data.length; i++) {
                var row = data[i];
                if (i > 0) {
                    row[1] = parseFloat(row[1]);
                }
                newData.push(row);
            }

            drawChart(newData);
        }
    });
}

google.load("visualization", "1", {
    packages: ["corechart"]
});
google.setOnLoadCallback(getData);

function drawChart(rawData) {
    /*var data = google.visualization.arrayToDataTable([
      ['Year', 'Sales', 'Expenses'],
      ['2004',  1000,      400],
      ['2005',  1170,      460],
      ['2006',  660,       1120],
      ['2007',  1030,      540]
    ]);*/

    var data = google.visualization.arrayToDataTable(rawData);

    var options = {
        title: 'Nuevos clientes'
    };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

    chart.draw(data, options);
}
</script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>