<script type="text/javascript">
    $(document).ready(function() {
        
        $("#datepicker_from").datepicker({
            dateFormat: "yy-mm-dd"
        });
        
        $("#datepicker_to").datepicker({
            dateFormat: "yy-mm-dd"
        });


        $("#payment_method_format").buttonset();
        $("#states_format").buttonset();
        
    });    
        
</script>

<div id="dates_panel" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Fecha</h3>
    </div>
      <div class="panel-body">
        Desde:
        <input type="text" id="datepicker_from">
        Hasta:
        <input type="text" id="datepicker_to">
    </div>
</div>

<div id="status_panel" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Status</h3>
    </div>
      <div class="panel-body">
        <div class="row">
                <?php
                    $statusCollection = $this->getStatus(); 
                    
                    $statusCollectionSplit = $this->partitionFilterArray($statusCollection); //array_chunk($statusCollection, 4);
                    
                    foreach ( $statusCollectionSplit AS $aStatusCollection ) {
                    
                ?>
                <div class="<?php echo $this->getColumnClass(); ?>">
                <?php
                        foreach ( $aStatusCollection AS $aStatus ) {
                ?>
                    <input type="checkbox" id="<?php echo $aStatus["status"]; ?>" value="<?php echo $aStatus["status"]; ?>" name="status[]" <?php echo $aStatus["checked"]; ?> />
                    <label for="<?php echo $aStatus["status"]; ?>"><?php echo $aStatus["label"]; ?></label>
                    <br />
                <?php
                        }
                ?>
                </div>
                <?php
                    }
                ?>
        </div>
    </div>
</div>

<div id="payment_method_panel" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Metodo de Pago</h3>
    </div>
      <div class="panel-body">
          <div class="row">
                <?php
                    $paymentMethodCollection = $this->getPaymentMethods(); 
                    
                    $paymentMethodCollectionSplit = $this->partitionFilterArray($paymentMethodCollection);
                    
                    foreach ( $paymentMethodCollectionSplit AS $aPaymentCollection ) {
                    
                ?>
                <div class="<?php echo $this->getColumnClass(); ?>">
                <?php
                        foreach ( $aPaymentCollection AS $aPayment ) {
                ?>
                    <input type="checkbox" id="<?php echo $aPayment["value"]; ?>" value="<?php echo $aPayment["value"]; ?>" name="payment_method[]" />
                    <label for="<?php echo $aPayment["value"]; ?>"><?php echo $aPayment["label"]; ?></label>
                    <br />
                <?php
                        }
                ?>
                </div>
                <?php
                    }
                ?>
        </div>
    </div>
</div>

<div id="states_panel" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Provincia</h3>
    </div>
      <div class="panel-body">
          <div class="row">
                <?php
                    $statesCollection = $this->getStates('AR');
                    
                    $statesCollectionSplit = $this->partitionFilterArray($statesCollection);
                    
                    foreach ( $statesCollectionSplit AS $aStatesCollection ) {
                    
                ?>
                <div class="<?php echo $this->getColumnClass(); ?>">
                <?php
                        foreach ( $aStatesCollection AS $aState ) {
                ?>
                    <input type="checkbox" id="<?php echo $aState["id"]; ?>" value="<?php echo $aState["id"]; ?>" name="state[]" />
                    <label for="<?php echo $aState["id"]; ?>"><?php echo $aState["name"]; ?></label>
                    <br />
                <?php
                        }
                ?>
                </div>
                <?php
                    }
                ?>
        </div>
    </div>
</div>

<div id="buttons">
    <button type="button" onclick="javascript:getData();">Ejecutar</button>
</div>