<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li id="menu_overview"><a href="<?php echo Mage::getUrl('helloworld/index'); ?>">Overview <span class="sr-only">(current)</span></a>
        </li>
        <li id="menu_sales_by_state"><a href="<?php echo Mage::getUrl('helloworld/index/salesByState'); ?>">Ventas por Provincia</a>
        </li>
        <li id="menu_sales_by_date"><a href="<?php echo Mage::getUrl('helloworld/index/salesByDate'); ?>">Ventas por Fecha</a>
        </li>
        <li id="menu_sales_by_year"><a href="<?php echo Mage::getUrl('helloworld/index/salesByYear'); ?>">Ventas por Año</a>
        <li id="menu_average_order_size">
            <a href="<?php echo Mage::getUrl('helloworld/index/averageOrderSize'); ?>">
                Average Order Size
            </a>
        </li>
        <li id="menu_average_order_volume">
            <a href="<?php echo Mage::getUrl('helloworld/index/averageOrderVolume'); ?>">
                Average Order Volume
            </a>
        </li>
        <li id="menu_sales_by_payment_method"><a href="<?php echo Mage::getUrl('helloworld/index/salesByPaymentMethod'); ?>">Ventas por Metodo de Pago</a>
        </li>
        <li id="menu_new_customers">
            <a href="<?php echo Mage::getUrl('helloworld/index/newCustomers'); ?>">
                Clientes Nuevos
            </a>
        </li>
    </ul>
    <ul class="nav nav-sidebar">
        <li id="menu_customer_ranking"><a href="<?php echo Mage::getUrl('helloworld/index/customerRanking'); ?>">Ranking de Cientes</a>
        </li>
        <li id="menu_cohort_analysis"><a href="<?php echo Mage::getUrl('helloworld/index/cohortAnalysis'); ?>">Cohort Analysis</a>
        </li>
        <li id="menu_cohort_analysis"><a href="<?php echo Mage::getUrl('helloworld/index/salesByDayAndHour'); ?>">Ventas por dia y hora</a>
        </li>
        <li id="menu_avg_sales_by_customer">
            <a href="<?php echo Mage::getUrl('helloworld/index/avgSalesByCustomer'); ?>">
                Gasto Total Promedio
            </a>
        </li>
        <li id="menu_sales_by_brand">
            <a href="<?php echo Mage::getUrl('helloworld/index/salesByBrand'); ?>">
                Ventas por Marca
            </a>
        </li>
    </ul>
</div>