<style>
  #format { margin-top: 2em; }
</style>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>

<script type="text/javascript" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>


    <script type="text/javascript">

        function getData() {
            
            $.ajax({
                type: "POST",
                url: "<?php echo Mage::getUrl('reports/data/getNewCustomers'); ?>",
                dataType: 'json',
                success: function(data) {

                    var newData = new Array();

                    var header = new Array(2);
                    header[0] = 'Periodo';
                    header[1] = 'Cantidad';
                    
                    newData.push(header);

                    for (var i = 0; i < data.length; i++) {

                        var newRow = new Array();
                    
                        newRow[0] = data[i].period;
                        newRow[1] = parseInt(data[i].qty, 10);
                        
                        newData.push(newRow);
                        
                        
                    }

                    drawChart(newData);
                    
                    createTable(data);

                }
            });
            
        }

        google.load("visualization", "1", {
            packages: ["corechart"]
        });
        
        google.setOnLoadCallback(getData);

        function drawChart(rawData) {
            var data = google.visualization.arrayToDataTable(rawData);

            var options = {
                title: 'Nuevos Clientes',
                'width':1000,
                'height':500
            };

            var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

            chart.draw(data, options);
        }
        
        function createTable(jsonData) {
            $('#new_customers_table').dataTable({
                "aaData": jsonData,
                "aoColumns": [
                                { "mDataProp": "period" },
                                { "mDataProp": "qty" }
                            ]
            });
        }

        $(document).ready(function() {

            var menuLink = document.getElementById("menu_new_customers");
            menuLink.className = "active";

        });
    
      
    </script>
    
    <h1 class="page-header">Nuevos Clientes</h1>
    
    <div class="row">
        <div class="col-md-12">
            <div id="chart_div" style="width: 900px; height: 500px; margin: 0 auto;"></div>
            
            <hr />
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-md-12">
            <div class="bs-example">
                <table id="new_customers_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Periodo</th>
                            <th>Clientes</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            
            <hr />
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div id="filters">
                <?php echo $this->getChildHtml('filters'); ?>
            </div>
        </div>
    </div>