<style>
  #format { margin-top: 2em; }
</style>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>

<script type="text/javascript" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>


    <script type="text/javascript">

        function getData() {
            
            $.ajax({
                type: "POST",
                url: "<?php echo Mage::getUrl('reports/data/getSalesByBrand'); ?>",
                dataType: 'json',
                success: function(data) {

                    var newData = new Array();

                    var header = new Array(2);
                    header[0] = 'Marca';
                    header[1] = 'Monto [ARS]';
                    
                    newData.push(header);

                    for (var i = 0; i < data.length; i++) {

                        var newRow = new Array();
                    
                        newRow[0] = data[i].brand;
                        newRow[1] = parseFloat(data[i].amount);
                        
                        newData.push(newRow);
                        
                        
                    }

                    drawChart(newData);
                    
                    createTable(data);

                }
            });
            
        }

        google.load("visualization", "1", {
            packages: ["corechart"]
        });
        
        google.setOnLoadCallback(getData);

        function drawChart(rawData) {
            var data = google.visualization.arrayToDataTable(rawData);

            var options = {
                title: 'Ventas por marca'
            };

            var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

            chart.draw(data, options);
        }
        
        function createTable(jsonData) {
            $('#avg_order_size_table').dataTable({
                "aaData": jsonData,
                "aoColumns": [
                                { "mDataProp": "brand" },
                                { "mDataProp": "amount" },
                                { "mDataProp": "qty" }
                            ]
            });
        }

        $(document).ready(function() {

            var menuLink = document.getElementById("menu_sales_by_brand");
            menuLink.className = "active";

        });
    
      
    </script>
    
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
    
    <div class="bs-example">
        <table id="avg_order_size_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Marca</th>
                    <th>Monto [ARS]</th>
                    <th># Ordenes</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    
    <div id="filters">
        <?php echo $this->getChildHtml('filters'); ?>
    </div>