<style>
  #format { margin-top: 2em; }
</style>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>


    <script type="text/javascript">

        function getData() {
            
            $( "#datepicker_from" ).datepicker( { dateFormat: "yy-mm-dd" } );
            $( "#datepicker_to" ).datepicker( { dateFormat: "yy-mm-dd" } );
            
            $( "#status_format" ).buttonset();
            $( "#payment_method_format" ).buttonset();
            
            var status = new Array();
            
            var chk_arr =  document.getElementsByName("status[]");
            var chklength = chk_arr.length;             
            
            for( var k=0;k< chklength;k++) {
                if ( chk_arr[k].checked === true ) {
                    status.push(chk_arr[k].id);
                }
            }
            
            var paymentMethod = new Array();
            
            chk_arr =  document.getElementsByName("payment_method[]");
            chklength = chk_arr.length;             
            
            for( var k=0;k< chklength;k++) {
                if ( chk_arr[k].checked === true ) {
                    paymentMethod.push(chk_arr[k].id);
                }
            }
            
            
            
            $.ajax({
                type: 'POST',
                data: {     date_from:  $( "#datepicker_from" ).val(), 
                            date_to :  $( "#datepicker_to" ).val(),
                            status: status,
                            payment_method: paymentMethod } ,
                url: '<?php echo Mage::getUrl('helloworld/index/getData'); ?>',
                dataType: 'json',
                success: function(data) {


                    var newData = new Array();

                    for (var i = 0; i < data.length; i++) {
                        var row = data[i];
                        if (i > 0) {
                            row[1] = parseInt(row[1], 10);
                            row[0] = decodeURIComponent(escape(row[0]));
                        }
                        newData.push(row);
                    }

                    drawChart(newData);
                    drawPieChart(newData);
                }
            });
        }

        google.load("visualization", "1", {
            packages: ["corechart"]
        });
        google.setOnLoadCallback(getData);

        function drawChart(rawData) {


            var data = google.visualization.arrayToDataTable(rawData);

            var options = {
                title: 'Ventas por Provincia',
                vAxis: {
                    title: 'Provincia',
                    titleTextStyle: {
                        color: 'red'
                    }
                }
            };

            var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

            chart.draw(data, options);
        }
        
        function drawPieChart(rawData) {
            var data = google.visualization.arrayToDataTable(rawData);
            var options = {
                title: 'Ventas por Provincia'
            };
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }

        $(document).ready(function() {
            
            var menuLink = document.getElementById("menu_sales_by_state");
            menuLink.className = "active";

        });
    
      
    </script>
    
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
    
    <div id="piechart" style="width: 900px; height: 500px;"></div>
    
    <div id="filters">
        <?php echo $this->getChildHtml('filters'); ?>
    </div>