<!-- DataTables CSS -->
<link href="http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<!-- DataTables JavaScript -->
<script src="http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>


<script type="text/javascript">

// Json data
var jsonData = null;

google.load('visualization', '1', {
    packages: ['corechart', 'bar']
});
google.setOnLoadCallback(getData);

function getCheckBoxFilter(attributeName) {
    
    var status = new Array();
            
    var chk_arr =  document.getElementsByName(attributeName);
    var chklength = chk_arr.length;             
            
    for( var k=0;k< chklength;k++) {
        if ( chk_arr[k].checked === true ) {
            status.push(chk_arr[k].id);
        }
    }
    
    return status;
    
}

function getData() {
    
    $( "#datepicker_from" ).datepicker( { dateFormat: "yy-mm-dd" } );
    $( "#datepicker_to" ).datepicker( { dateFormat: "yy-mm-dd" } );
    
    var status = getCheckBoxFilter("status[]");
    var paymentMethod = getCheckBoxFilter("payment_method[]");
    var state = getCheckBoxFilter("state[]");

    $.ajax({
        type: "POST",
        url: "<?php echo Mage::getUrl('reports/salesData/getAverageOrder'); ?>",
        data: { 
                date_from:  $( "#datepicker_from" ).val(), 
                date_to :  $( "#datepicker_to" ).val(),
                status: status,
                payment_method: paymentMethod,
                state: state} ,
        dataType: 'json',
        success: function(data) {
            
            jsonData = data;

            var newData = new Array();

            var header = new Array(2);
            header[0] = 'Periodo';
            header[1] = 'Monto [ARS]';

            newData.push(header);

            var dataLength = data.length;

            for ( var i = 0; i < dataLength; i++ ) {
                    
                var newRow = new Array();

                newRow[0] = data[i].period;
                newRow[1] = parseFloat(data[i].amount);
                        
                newData.push(newRow);
                
            }

            drawChart(newData);

            createTable(data);

        }
    });

}

function createTable(jsonData) {
        $('#datatable').dataTable({
            "aaData": jsonData,
            "aoColumns": [{
                "mDataProp": "period"
            }, {
                "mDataProp": "qty"
            }, {
                "mDataProp": "amount"
            }, {
                "mDataProp": "qtyPerOrder"
            }]
        });
    }

function drawChart(rawData) {
    
    var data = google.visualization.arrayToDataTable(rawData);

    var options = {
                title: 'Orden promedio',
                height: 500
            };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

    chart.draw(data, options);
}

function formatData(attribute) {

    var dataLength = jsonData.length;
    
    var newData = new Array();

    var header = new Array(2);
    header[0] = 'Periodo';
    
    if ( attribute === "amount" ) {
        header[1] = 'Monto [ARS]';
    }
    else if ( attribute === "qtyPerOrder" ) {
        header[1] = 'Cantidad';
    }
    else {
        header[1] = '';
    }

    newData.push(header);

    for ( var i = 0; i < dataLength; i++ ) {
                    
        var newRow = new Array();

        newRow[0] = jsonData[i].period;
        newRow[1] = parseFloat(jsonData[i][attribute]);
                        
        newData.push(newRow);
                
    }
    
    drawChart(newData);
}

</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->__('Orden promedio'); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Opciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="javascript:formatData('amount');">Monto</a>
                            </li>
                            <li><a href="javascript:formatData('qtyPerOrder');">Cantidad</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="chart_div"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                DataTables Advanced Tables
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table id="datatable" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Periodo</th>
                                <th># Ordenes</th>
                                <th>Monto [ARS]</th>
                                <th>Promedio [ARS]</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->getChildHtml('filters') ?>
    </div>
    <!-- /.col-lg-4 -->
</div>
<!-- /.row -->

<script type="text/javascript">
    jQuery(function($) {
        $('.panel-heading span.clickable').on("click", function(e) {
            if ($(this).hasClass('panel-collapsed')) {
                // expand the panel
                $(this).parents('.panel').find('.panel-body').slideDown();
                $(this).removeClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            }
            else {
                // collapse the panel
                $(this).parents('.panel').find('.panel-body').slideUp();
                $(this).addClass('panel-collapsed');
                $(this).find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');
            }
        });
    });
</script>